site_name: dp
theme : simplex
use_directory_urls : false
markdown_extensions: [extra]
docs_dir : doc
pages:
- [index.md, Home]
- [neuralnetworktutorial.md, Tutorial, Neural Network Tutorial]
- [facialkeypointstutorial.md, Tutorial, Facial Keypoints Tutorial]
- [view.md, Data Library, View]
- [data.md, Data Library, Data]
- [preprocess.md, Data Library, Preprocess] 
- [node.md, Node Library, Node]
- [model.md, Node Library, Model]
- [loss.md, Node Library, Loss]
- [experiment.md, Experiment Library, Experiment]
- [propagator.md, Experiment Library, Propagator]
- [visitor.md, Experiment Library, Visitor] 
- [feedback.md, Extensions, Feedback]
- [observer.md, Extensions, Observer]
- [mediator.md, Extensions, Mediator]


